name: 'ASU - Applications'
type: module
description: 'Logic related to apartment applications'
core: 8.x
core_version_requirement: ^8 || ^9
package: 'ASU'
libraries:
  - 'asu_application/application-results.js'
