additional-applicant:
  version: 1.x
  js:
    assets/js/additional-applicant.js: {}
application_submit:
  version: 1.x
  js:
    assets/js/application-submit.js: {}
  dependencies:
    - core/jquery
    - core/drupal.dialog
    - core/drupal
    - core/once
