_core:
  default_config_hash: P6YjZQN0wv2MHVDNRVc46Plx_OiZFESe-I78R-ovdVQ
from-morelink: 'https://google.fi'
popup-morelink: /gdpr-compliance/policy
popup-text-cookies: ''
popup-text-analytics: ''
popup-btn-agree: ''
popup-btn-findmore: ''
user-register: 1
user-login: 0
contact_message-mode: null
contact_message-bundles: null
node-mode: disable
node-bundles:
  article: 0
  landing_page: 0
  page: 0
  service: 0
  unit: 0
webform-mode: null
webform-bundles: null
popup-guests: 0
popup-users: 0
popup-position: bottom
popup-custom-color: 0
popup-color: '#1157cc'
popup-text: white
button-color: '#fde143'
button-text: black
